# Generated by Django 5.2 on 2026-06-30 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_products'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
